// Codes from: https://api.met.no/weatherapi/locationforecast/2.0/swagger
export const POLISH_DESCRIPTION_BY_SYMBOL_CODE: {
    [key: string] : string,
} = {
    clearsky_day: 'Bezchmurne niebo',
    clearsky_night: 'Bezchmurne niebo',
    clearsky_polartwilight: 'Bezchmurne niebo (polarna zmierzch)',
    fair_day: 'Czyste niebo',
    fair_night: 'Czyste niebo',
    fair_polartwilight: 'Czyste niebo (polarna zmierzch)',
    lightssnowshowersandthunder_day: 'Światłośnieżyce i burze',
    lightssnowshowersandthunder_night: 'Światłośnieżyce i burze',
    lightssnowshowersandthunder_polartwilight: 'Światłośnieżyce i burze (polarna zmierzch)',
    lightsnowshowers_day: 'Lekkie opady śniegu',
    lightsnowshowers_night: 'Lekkie opady śniegu',
    lightsnowshowers_polartwilight: 'Lekkie opady śniegu (polarna zmierzch)',
    heavyrainandthunder: 'Ulewny deszcz i burze',
    heavysnowandthunder: 'Ulewny śnieg i burze',
    rainandthunder: 'Deszcz i burze',
    heavysleetshowersandthunder_day: 'Intensywne opady deszczu ze śniegiem i burze',
    heavysleetshowersandthunder_night: 'Intensywne opady deszczu ze śniegiem i burze',
    heavysleetshowersandthunder_polartwilight: 'Intensywne opady deszczu ze śniegiem i burze (polarna zmierzch)',
    heavysnow: 'Intensywne opady śniegu',
    heavyrainshowers_day: 'Ulewny deszcz',
    heavyrainshowers_night: 'Ulewny deszcz',
    heavyrainshowers_polartwilight: 'Ulewny deszcz (polarna zmierzch)',
    lightsleet: 'Lekkie opady deszczu ze śniegiem',
    heavyrain: 'Ulewny deszcz',
    lightrainshowers_day: 'Lekkie opady deszczu',
    lightrainshowers_night: 'Lekkie opady deszczu',
    lightrainshowers_polartwilight: 'Lekkie opady deszczu (polarna zmierzch)',
    heavysleetshowers_day: 'Ulewny deszcz ze śniegiem',
    heavysleetshowers_night: 'Ulewny deszcz ze śniegiem',
    heavysleetshowers_polartwilight: 'Ulewny deszcz ze śniegiem (polarna zmierzch)',
    lightsleetshowers_day: 'Lekkie opady deszczu ze śniegiem',
    lightsleetshowers_night: 'Lekkie opady deszczu ze śniegiem',
    lightsleetshowers_polartwilight: 'Lekkie opady deszczu ze śniegiem (polarna zmierzch)',
    snow: 'Opady śniegu',
    heavyrainshowersandthunder_day: 'Ulewny deszcz i burze',
    heavyrainshowersandthunder_night: 'Ulewny deszcz i burze',
    heavyrainshowersandthunder_polartwilight: 'Ulewny deszcz i burze (polarna zmierzch)',
    snowshowers_day: 'Opady śniegu',
    snowshowers_night: 'Opady śniegu',
    snowshowers_polartwilight: 'Opady śniegu (polarna zmierzch)',
    fog: 'Mgła',
    snowshowersandthunder_day: 'Opady śniegu i burze',
    snowshowersandthunder_night: 'Opady śniegu i burze',
    snowshowersandthunder_polartwilight: 'Opady śniegu i burze (polarna zmierzch)',
    lightsnowandthunder: 'Lekkie opady śniegu i burze',
    heavysleetandthunder: 'Ulewny deszcz ze śniegiem i burze',
    lightrain: 'Lekkie opady deszczu',
    rainshowersandthunder_day: 'Opady deszczu i burze',
    rainshowersandthunder_night: 'Opady deszczu i burze',
    rainshowersandthunder_polartwilight: 'Opady deszczu i burze (polarna zmierzch)',
    rain: 'Deszcz',
    lightsnow: 'Lekkie opady śniegu',
    lightrainshowersandthunder_day: 'Lekkie opady deszczu i burze',
    lightrainshowersandthunder_night: 'Lekkie opady deszczu i burze',
    lightrainshowersandthunder_polartwilight: 'Lekkie opady deszczu i burze (polarna zmierzch)',
    heavysleet: 'Ulewny deszcz ze śniegiem',
    sleetandthunder: 'Opady deszczu ze śniegiem i burze',
    lightrainandthunder: 'Lekkie opady deszczu i burze',
    sleet: 'Opady deszczu ze śniegiem',
    lightssleetshowersandthunder_day: 'Światłośnieżne opady deszczu ze śniegiem i burze',
    lightssleetshowersandthunder_night: 'Światłośnieżne opady deszczu ze śniegiem i burze',
    lightssleetshowersandthunder_polartwilight: 'Światłośnieżne opady deszczu ze śniegiem i burze (polarna zmierzch)',
    lightsleetandthunder: 'Lekkie opady deszczu ze śniegiem i burze',
    partlycloudy_day: 'Częściowe zachmurzenie',
    partlycloudy_night: 'Częściowe zachmurzenie',
    partlycloudy_polartwilight: 'Częściowe zachmurzenie (polarna zmierzch)',
    sleetshowersandthunder_day: 'Opady deszczu ze śniegiem i burze',
    sleetshowersandthunder_night: 'Opady deszczu ze śniegiem i burze',
    sleetshowersandthunder_polartwilight: 'Opady deszczu ze śniegiem i burze (polarna zmierzch)',
    rainshowers_day: 'Opady deszczu',
    rainshowers_night: 'Opady deszczu',
    rainshowers_polartwilight: 'Opady deszczu (polarna zmierzch)',
    snowandthunder: 'Opady śniegu i burze',
    sleetshowers_day: 'Opady deszczu ze śniegiem',
    sleetshowers_night: 'Opady deszczu ze śniegiem',
    sleetshowers_polartwilight: 'Opady deszczu ze śniegiem (polarna zmierzch)',
    cloudy: 'Zachmurzenie',
    heavysnowshowersandthunder_day: 'Ulewny opady śniegu i burze',
    heavysnowshowersandthunder_night: 'Ulewny opady śniegu i burze',
    heavysnowshowersandthunder_polartwilight: 'Ulewny opady śniegu i burze (polarna zmierzch)',
    heavysnowshowers_day: 'Ulewny opady śniegu',
    heavysnowshowers_night: 'Ulewny opady śniegu',
    heavysnowshowers_polartwilight: 'Ulewny opady śniegu (polarna zmierzch)',
};
